LibCal:
  client_id: 
  client_secret: 
  locations:
    - name: 'Gelman Library Study Spaces'
      id: 8827
    - name: 'Virginia Science & Technology Campus Library'
      id: 10332
  credentials_endpt: 'https://booking.library.gwu.edu/1.1/oauth/token'
  bookings_endpt: 'https://booking.library.gwu.edu/1.1/space/bookings'
  primary_id_field: q12505
Alma:
  apikey: 
  users_endpt: 'https://api-na.hosted.exlibrisgroup.com/almaws/v1/users'
PassagePoint:
  username: 
  password: 
  pp_api_root: 'https://passagepoint.at.gwu.edu:2444'
  login_endpt: '/pp/api/v2/auth/login'
  uniqueId_endpt: '/pp/api/v2/person/byUniqueId'
  create_visitor_endpt: '/pp/api/v2/person/createVisitor'
  create_prereg_endpt: '/pp/api/v2/visit/createPreReg'
  get_destinations_endpt: 'pp/api/v2/visit/getDestinations'
  location_mapping:
      8827: 'LibCal Gelman'
      10332: 'LibCal VSTCL'
  user_mapping:
    gw und: Student
    gw grad: Student
    gw fac: Faculty
    gw stf1: Staff
    gw stf2: Staff
    gw ocg: Student